import Head from "next/head";
import React, { FC, useEffect, useRef, useState } from "react";

type Props = {
    children: React.ReactNode;
}

const BackgroundLayout: FC<Props> = ({children}) => {

    const bg = useRef<HTMLDivElement>(null);
    const [animAmt, setAnimAmt] = useState(.5);

    useEffect(() => {
        if(!bg.current) return;
        bg.current.style.opacity = animAmt.toString();
        window.addEventListener("mousemove", (e) => {
            if(!bg.current) return;
            let amt = (window.innerHeight - (e.clientY + 300) * .5) / window.innerHeight;
            if(amt > 1 || amt < 0) {
                amt = Math.round(amt);
            }
            setAnimAmt(amt);
            bg.current.style.opacity = amt.toString();
        })
    }, [bg])

    return (
        <div className="h-screen">
        <Head>
            <title>Steam Higher Lower</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div ref={bg} className="fixed -z-10 bg-top-gradient w-full h-screen"></div>
        <div className="fixed -z-20 bg-bottom-gradient w-full h-screen"></div>
        {children}
      </div>
    )
}

export default BackgroundLayout;