import Head from "next/head";
import React, { FC } from "react";

type Props = {
    children: React.ReactNode;
}

const BaseLayout: FC<Props> = ({children}) => {
    return (
        <div className="h-screen">
        <Head>
            <title>Steam Higher Lower</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
      </div>
    )
}

export default BaseLayout;