import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {

  return (
    <div className={`container mx-auto h-screen`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto flex flex-col items-center h-full">
        <div className="my-9">
          <Image
            src="/images/steam_logo.svg"
            alt="steam logo"
            width="400"
            height="120"
            className="inline-block"
          ></Image>
          <span className="inline-block text-2xl">Charts</span>
        </div>
        <h1 className="text-4xl my-20">
          Higher Lower <span className="block text-center my-2">Game</span>
        </h1>
        <Link className={`bg-cyan-800 my-32 py-2 text-3xl text-white rounded-lg w-40 text-center`} href="/classic">Play</Link>
      </div> 
    </div>
  );
}
