import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const wordGradient = "text-transparent bg-clip-text";

export default function Home() {
  return (
    <div className={`container mx-auto h-screen`}>
      <Head>
        <title>Steam Higher Lower</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-auto flex flex-col justify-center items-center h-3/4">
        <h1 className="my-9 text-transparent text-8xl bg-clip-text bg-gradient-to-br from-blue-600 to-black">
          Steam
          <span className="inline-block text-6xl bg-clip-text bg-gradient-to-br from-blue-900 to-blue-600">
            Charts
          </span>
        </h1>
        <h2 className="text-6xl my-20 py-4 text-center">
          <span className="text-transparent bg-clip-text bg-gradient-to-b from-white to-blue-600">
            Higher
          </span>
          <span className="block mt-6 text-transparent bg-clip-text bg-gradient-to-b from-red-600 to-gray-700">
            Lower
          </span>
        </h2>
        <Link
          className={`bg-cyan-800 py-2 text-3xl text-white rounded-lg w-40 text-center`}
          href="/classic"
        >
          Play
        </Link>
      </div>
    </div>
  );
}
