name: daily-cron
on:
  schedule:
    - cron: '*/10 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call steam game api route
        run: |
          curl --request POST \
          --url 'https://steam-higher-lower.vercel.app/api/steamgames' \
          --header 'Authorization: ${{ secrets.API_SECRET_KEY }}'