name: minutely-cron
on:
  schedule:
    - cron: '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://steam-higher-lower.vercel.app/api/playercounts' \
          --header 'Authorization: Bearer ${{ secrets.API_SECRET_KEY }}'